// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetUser.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, name, created_at 
FROM users
WHERE name = $1
`

type GetUserRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) GetUser(ctx context.Context, name string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, name)
	var i GetUserRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
